:lipstick: #971 - The styling of the select widget with multiple valu…
open-formulieren/open-forms-sdk pull request #119
Opened 2021-11-26 11:58 UTC by svenvandescheur

…es is off.

2021-11-26 11:59 UTC, svenvandescheur commented
![Schermafbeelding 2021-11-26 om 12 59 30](https://user-images.githubusercontent.com/10243534/143577764-58329074-59ea-40db-a058-4aed5a6cb69a.png)

2021-11-26 16:57 UTC, sergei-maertens requested changes

2021-11-26 16:57 UTC, sergei-maertens commented on src/scss/components/_select.scss
> +  $item-margin: $grid-margin-0/2;
```suggestion
  $item-margin: math.div($grid-margin-0, 2);
```

2021-11-26 16:57 UTC, sergei-maertens commented on src/scss/components/_select.scss
> +    display: flex;
can you please keep `display: flex` and `align-items` grouped together, as they both apply to the flexbox layout

now it's harder to read how the layout is defined.

2021-11-29 09:43 UTC, sergei-maertens approved these changes

2021-11-29 09:44 UTC, sergei-maertens commented
Some more tweaks

![image](https://user-images.githubusercontent.com/5518550/143844591-2d63c257-e8be-45e6-9a50-a23fc5b88408.png)

2021-11-29 09:50 UTC, merged