Better file upload errors styling
open-formulieren/open-forms-sdk pull request #162
Opened 2022-02-09 16:24 UTC by sergei-maertens

Fixes open-formulieren/open-forms#1193
Fixes open-formulieren/open-forms#1316

There are some mistakes in the core templates, so it's time to override it anyway. In the future we can use this to properly style this to our liking, as the bootstrap markup/classes makes this hard and annoying to deal with.

![image](https://user-images.githubusercontent.com/5518550/153244149-15b5017e-1e10-48b8-b4cb-c61f1ca4f03c.png)

2022-02-10 12:32 UTC, SilviaAmAm requested changes
I notice a few problems when trying out the file field in the form:
- It is now possible to upload multiple files in a file field without a 'multiple' selected.
- If the name of the file is very long, then it looks funny (see screenshot 1)
- If the file component is inside a field set and the name of the updated file is long, the whole field set goes off the page  (see screenshot 2). This problem though was pre-existing: https://github.com/open-formulieren/open-forms/issues/1316


![Screenshot from 2022-02-10 13-31-22](https://user-images.githubusercontent.com/19154114/153409140-b4bab606-2005-45bc-8920-0621fcc96064.png)

![Screenshot from 2022-02-10 13-31-57](https://user-images.githubusercontent.com/19154114/153409220-67087b62-f578-485b-abf6-99f28d4bc9e3.png)

2022-02-10 15:16 UTC, sergei-maertens commented
@SilviaAmAm I think I've fixed fieldsets, can you confirm?

2022-02-11 09:22 UTC, sergei-maertens commented
Default formio behaviour seems to be that the file is left there and you have to remove it itself by clicking the cross, and other files dragged into the box are validated/uploaded separately.

2022-02-11 09:27 UTC, SilviaAmAm approved these changes

2022-02-11 09:50 UTC, joeribekker approved these changes

2022-02-11 15:06 UTC, merged