Remove accidental styling of content components
open-formulieren/open-forms-sdk pull request #241
Opened 2022-09-26 12:59 UTC by SilviaAmAm

Fixes open-formulieren/open-forms#2073

2022-09-27 08:47 UTC, SilviaAmAm commented
Noticed that this shows a red rectangle by (valid) repeating groups. Need to fix.

2022-09-28 13:01 UTC, sergei-maertens requested changes

2022-09-28 13:01 UTC, sergei-maertens commented on src/scss/components/_form-control.scss
> +  .error {
This results in the CSS rule `.openforms-form-control .error` rather than `.openforms-form-control.error` - is that intentional?

2022-09-28 14:06 UTC, sergei-maertens approved these changes

2022-09-28 14:06 UTC, merged