[Draft] :truck: [#2232] Rename i18nEnabled -> translationEnabled
open-formulieren/open-forms-sdk pull request #272
Opened 2022-10-31 10:48 UTC by stevenbal

since the djangorestframework-camel-case parser does not seem to parse i18nEnabled properly (it results in i_18n_enabled)

2022-10-31 10:52 UTC, stevenbal commented
@sergei-maertens it seems that the camelcase parser for DRF parses `i18nEnabled` to `i_18n_enabled` and I didn't want to deal with that, so I renamed the field

2022-11-04 10:42 UTC, sergei-maertens requested changes

2022-11-04 10:42 UTC, sergei-maertens commented on src/sdk.js
> +      post(`${formObject.url}/set_default_language`);
```suggestion
      await post(`${formObject.url}/set_default_language`);
```

2022-11-07 11:47 UTC, sergei-maertens approved these changes

2022-11-07 11:47 UTC, merged