Conditionally render language selection component
open-formulieren/open-forms-sdk pull request #277
Opened 2022-11-09 18:33 UTC by CharString

Closes open-formulieren/open-forms#2254

2022-11-09 18:38 UTC, CharString commented on src/components/App.stories.mdx
> +*/
Very disorienting to debug this... One thing I learned is that whitespace is significant.

2022-11-10 10:40 UTC, CharString commented
May need another rebase on the branch attached to #273.

2022-11-10 15:11 UTC, sergei-maertens requested changes
I'll apply the changes and merge the PR

2022-11-10 15:11 UTC, sergei-maertens commented on src/components/App.js
> +  if (!renderSelector) return (<></>);
`return null` is more idiomatic in react instead of using an empty fragment.

2022-11-10 15:11 UTC, sergei-maertens commented on src/components/App.js
> +      <LanguageSwitcher target={languageSelectorTarget} renderSelector={props.form.translationEnabled} />
it makes a bit more sense to decide not to render a node in the parent (`App` in this case) if you only pass along that information:

```jsx
{props.form.translationEnabled ? <LanguageSwitcher ... /> : null}
```

2022-11-10 15:14 UTC, sergei-maertens approved these changes

2022-11-10 15:14 UTC, sergei-maertens commented on src/components/App.js
> +  form: Types.Form,
we have some re-usable prop types defined in the `types` package :)

2022-11-10 15:21 UTC, merged