Load translations onLanguageChanged
open-formulieren/open-forms-sdk pull request #281
Opened 2022-11-14 15:19 UTC by CharString

- Adds I18NManager to cantain all language string loading and signalling re-renders.
 - Moves `onLanguageChanged` callback from `LanguageSelection` params to `ConfigContext`
   
 Closes open-formulieren/open-forms#2255

2022-11-14 15:30 UTC, CharString commented
Flatpickr seems to automagically change. I don't know what triggers it, but on every language change it will add a new node to the DOM with a new flatpickr script with the new locale. It even keeps working if I remove this line: 
https://github.com/open-formulieren/open-forms-sdk/blob/5e41548abd4ddae4e236909ae04ae43275d4db0a/src/sdk.js#L94
I tried to find the magic, because it doesn't clean up the previous nodes, but I gave up.

Also tried to get
https://github.com/open-formulieren/open-forms-sdk/blob/5e41548abd4ddae4e236909ae04ae43275d4db0a/src/i18n.js#L14-L21
to use `import()` such that it will load strings dynamically and async to reduce main bundle size. But `try {} catch {}` doesn't catch the import errors that can occur.

2022-11-17 10:06 UTC, sergei-maertens requested changes
I'm not a fan of hardcoding the App in this container component, why not use `props.children` instead?

We now have a component called `I18NManager` doing much more than that - it's also rendering the app, loading the form details from the API which is really the responsibility of other components that need to be composed.

I'll see if I can come to a set up that is more loosely coupled

2022-11-17 10:06 UTC, sergei-maertens commented on src/components/LanguageSelection/LanguageSelection.stories.mdx
> -    onLanguageChanged: { table: { disable: true } },
this arg is not relevant for the `LanguageSelectionDisplay` component and you can't change it in the controls anyway, that's why I disabled it for the canvas.

2022-11-17 10:06 UTC, sergei-maertens commented on src/i18n.js
> +    case "nl":
please keep the code style consistent with existing code style in the file - we'll implement prettier for the SDK at some point, but javascript strings are generally single quote, while JSX props use double quotes.

These sort of formatting changes really clutter the diff and make reviewing harder.

2022-11-18 11:35 UTC, closed without merging