:memo: 306 add Storybook Content component
open-formulieren/open-forms-sdk pull request #315
Opened 2022-12-10 15:59 UTC by jiromaykin

Fixes open-formulieren/open-forms-sdk#306

2022-12-13 11:50 UTC, sergei-maertens requested changes
I'd also like to see an arg for the configuration option "Aangepaste CSS class" from the form designer.

2022-12-14 08:17 UTC, sergei-maertens requested changes

2022-12-14 08:17 UTC, sergei-maertens commented on src/formio/components/Content.stories.mdx
> +      customClass: 'breed',
this arg will have to be added to the `argTypes` above - the allowed list of values is limited in the backend: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/js/components/form/content.js#L13

You can use the control type of `radio` for this, see https://github.com/open-formulieren/open-forms-sdk/blob/main/src/components/ProgressIndicator/index.stories.mdx?plain=1#L13 for an example

2022-12-15 08:44 UTC, jiromaykin commented
Squashed some commits.

2022-12-15 14:23 UTC, merged