[#2875] fix siteimprove
open-formulieren/open-forms-sdk pull request #387
Opened 2023-03-31 09:06 UTC by pi-sigma

Fixes open-formulieren/open-forms#2875

*send full URL to siteimprove instead of path

2023-03-31 09:18 UTC, pi-sigma commented
Relevant documenation

Hooks for obtaining (previous) location:
* https://reactrouter.com/en/main/hooks/use-location
* https://usehooks.com/usePrevious/

API reference for the `location` object:
* https://github.com/remix-run/history/blob/main/docs/api-reference.md#location
* https://github.com/remix-run/history/blob/main/docs/getting-started.md#listening

2023-04-03 14:44 UTC, sergei-maertens commented
@pi-sigma to verify this fix, can you please:

1. push a git tag for this branch commit (e.g. `issue-2875`)
2. create a PR in the backend where `.sdk-release` is updated with the tag from 1.
3. create a tag for that backend branch/PR and push it (e.g. `2.1.1-issue2875`)

We can then deploy that tag to an environment to test if these changes work

2023-04-18 09:50 UTC, sergei-maertens commented
Quick test findings

After accepting cookies & refreshing the form start page:

![image](https://user-images.githubusercontent.com/5518550/232740204-7d2be517-17e6-4900-b276-c50ea939642a.png)

This also happens when navigating using the next/previous buttons.

2023-04-18 09:56 UTC, sergei-maertens commented
For local debugging: `window._sz = {push: function() {}}`

2023-04-18 13:34 UTC, sergei-maertens requested changes

2023-04-18 13:34 UTC, sergei-maertens commented on src/hooks/usePageViews.js
> +        url: window.location.origin + location.pathname,
Can you please re-add the `location.hash.substring(1)` part too?

```suggestion
        url: window.location.origin + location.pathname + location.hash.substring(1),
```

2023-04-18 13:34 UTC, sergei-maertens commented on src/hooks/usePageViews.js
> +        ref: previousLocation && window.location.origin + previousLocation.pathname,
```suggestion
        ref: previousLocation && window.location.origin + previousLocation.pathname + previousLocation.hash.substring(1),
```

2023-04-18 13:34 UTC, sergei-maertens commented on src/hooks/usePageViews.js
>    const promises = Object.values(ANALYTICS_PROVIDERS).map(callback => callback(location));
```suggestion
  const promises = Object.values(ANALYTICS_PROVIDERS).map(callback => callback(location, previousLocation));
```
you still need to actually pass the argument to the analytics-specific function too

2023-04-18 13:34 UTC, sergei-maertens commented on src/hooks/usePageViews.js
> +function usePrevious(value) {
do we still need this custom usePrevious?

2023-04-19 12:28 UTC, sergei-maertens approved these changes

2023-04-19 12:28 UTC, merged

2023-04-19 12:32 UTC, sergei-maertens commented
Backported via: e47627f4f4b192692d8a92b115ffe833535cd0ce and e8d40c384b57a370cf8f0f81f39c1994f1fd7c1b