[#2809] make report download link title configurable
open-formulieren/open-forms-sdk pull request #424
Opened 2023-05-22 07:27 UTC by pi-sigma

Related to open-formulieren/open-forms#2809
Complement to open-formulieren/open-forms#3108

- Changed `components.SubmissionConfirmation.js` to use dynamic title for download link

2023-05-24 10:43 UTC, CharString reviewed
Hard to judge if this is correct with the API not fleshed out. open-formulieren/open-forms#3108
This change assumes there's always a translated link title in the api response.

2023-05-25 12:02 UTC, pi-sigma commented
@CharString The global config has a default for the title ([link](https://github.com/open-formulieren/open-forms/blob/f4adc9a4d21d18fdce554eb2851628bbb856ce09/src/openforms/config/models.py#L71))

2023-06-01 10:02 UTC, sergei-maertens requested changes

2023-06-01 10:02 UTC, sergei-maertens commented on src/components/SubmissionConfirmation.js
> +            {form.submissionReportDownloadLinkTitle}
Let's take a conservative and backwards compatible approach here - try to get the value from the API endpoint, but if it's falsy, fall back to the existing `<FormattedMessage>` approach. I don't think this change warrants an SDK major version bump.

2023-06-05 08:43 UTC, sergei-maertens requested changes

2023-06-05 08:43 UTC, sergei-maertens commented on src/components/SubmissionConfirmation.js
> +const SubmissionConfirmation = ({statusUrl, onFailure, onConfirmed, submission, form}) => {
`submission` prop is unused, and `form` prop should be added to the component prop types.

2023-06-05 08:43 UTC, sergei-maertens commented on src/components/SubmissionConfirmation.js
> +  }
I don't think this will throw an error, since `form` is an object, `linkTitle` will just resolve to `undefined` if the attribute is not present.

2023-06-06 08:40 UTC, sergei-maertens approved these changes

2023-06-06 08:40 UTC, merged