:sparkles: [#2175] added configureable zoom and start location
open-formulieren/open-forms-sdk pull request #488
Opened 2023-07-11 06:54 UTC by bart-maykin

fixes open-forms issue: [2175](https://github.com/open-formulieren/open-forms/issues/2175)

- retrieved default zoom and location from configuration
- set starting location as configured latitude and longitude 
- set starting zoomlevel to be either map default or the configured zoomlevel

2023-07-11 12:12 UTC, sergei-maertens requested changes

2023-07-11 12:12 UTC, sergei-maertens commented on src/formio/components/Map.js
>      );
this isn't correct - the marker implies the select location and when no default value is provided, there just initially are no coordinates selected. Therefor, `markerCoordinates` can still be `null`.

It looks like you're trying to use `markerCoordinates` to set the center of the map view, but that's an entirely separate concept/prop that should be added.

2023-07-14 10:25 UTC, bart-maykin commented on src/components/Map/index.js
> +          <MapView coordinates={defaultCenter} zoomLevel={defaultZoomLevel} />
Double check if this doesn't reset the center view and zoom level when user places a marker.

2023-07-14 10:29 UTC, bart-maykin commented on src/formio/components/Map.js
> +        : DEFAULT_LAT_LON;
maybe

```js
const [defaultLat, defaultLon] = DEFAULT_LAT_LON;
const {lat = defaultLat, lng = defaultLon} = this.component?.initalCenter || {};
const defaultCenter = [lat, lng];
```

2023-07-14 10:37 UTC, bart-maykin commented on src/components/Map/Map.stories.js
> +    defaultCenter: [52.1326332, 5.291266],
changing this does not appear to have an effect in storybook -> check if it's also in the component itself but either way this should work as expected

2023-07-14 22:07 UTC, sergei-maertens approved these changes

2023-07-14 22:07 UTC, merged