:heavy_plus_sign: [#2176] added gesture handling for leaflet
open-formulieren/open-forms-sdk pull request #519
Opened 2023-07-28 16:33 UTC by bart-maykin

Fixes https://github.com/open-formulieren/open-forms/issues/2176

- Added leaflet-gesture-handling
- Implemented leaflet-gesture-handling
- removed zoomlevel as a argument from the setView in the MapView component

2023-07-28 17:29 UTC, bart-maykin commented
Jest tests seem to be failing because Leaflet (L) is not defined in the index.js file.

![Screenshot from 2023-07-28 19-29-03](https://github.com/open-formulieren/open-forms-sdk/assets/101265650/6709835e-9b66-4d7f-95ab-2052fef625d3)

2023-08-02 15:23 UTC, sergei-maertens requested changes
Some more general remarks:

* https://github.com/elmarquis/Leaflet.GestureHandling/issues/86 -> when switching the language in storybook, I'm only seeing English messages and never Dutch, that's wrong behaviour
* There's not a lot of activity in the library/repository, so this is a bit of a risk :thinking: if it works well, we can accept the risk
* https://github.com/elmarquis/Leaflet.GestureHandling/issues/65 is concerning, have you seen similar behaviour?

2023-08-02 15:23 UTC, sergei-maertens commented on src/components/Map/index.js
> +  map.addHandler('gestureHandling', GestureHandling);
this is really something that you can't do with react components - every render means this function gets executed every time, and we are not (nor shouldn't be) in control of when renders happen - that's a React internal.

Effectively, running this kind of initialization during the render is a bad idea - it belongs in a `useEffect` that only runs once, or better (from https://github.com/elmarquis/Leaflet.GestureHandling/issues/65), it appears you can run:

```js
L.Map.addInitHook("addHandler", "gestureHandling", GestureHandling);
```
this looks a lot like a global, so perhaps we can even move that out of react alltogether (and put it in `src/map/index.js`) and handle it similarly to `fixIconUrls`.

2023-08-02 15:23 UTC, sergei-maertens commented on src/components/Map/index.js
> +
so the previous PR removed the blank line, and this one adds it back? :stuck_out_tongue: 

Please avoid these kind of cosmetic changes that only clutter the diff :wink:

2023-08-02 15:23 UTC, sergei-maertens commented on src/scss/components/_leaflet-map.scss
> +@import 'leaflet-gesture-handling/dist/leaflet-gesture-handling.css';
please pay attention to the import ordering - you can see that there already is a leaflet-related CSS import at the top. This belongs directly below it (sorting alphabetically).

In general, we follow the pattern: stdlib / third party dependencies / own project / relative imports for the import groups.

2023-08-04 07:44 UTC, bart-maykin commented
> Some more general remarks:
> 
>     * [Wrong default language - WCAG 3.1.2 failure elmarquis/Leaflet.GestureHandling#86](https://github.com/elmarquis/Leaflet.GestureHandling/issues/86) -> when switching the language in storybook, I'm only seeing English messages and never Dutch, that's wrong behaviour
> 
>     * There's not a lot of activity in the library/repository, so this is a bit of a risk thinking if it works well, we can accept the risk
> 
>     * [two finger drag / page scroll prevention and glitchy panning elmarquis/Leaflet.GestureHandling#65](https://github.com/elmarquis/Leaflet.GestureHandling/issues/65) is concerning, have you seen similar behaviour?

- I added react-intel translations which seem to fix the translation problem.
- I looked at the video capture that he provided and from what I can see we are not running into the same problems. But maybe it would be good if you double check for me with the storybook build in this pr.

2023-08-04 09:57 UTC, sergei-maertens approved these changes

2023-08-04 09:58 UTC, sergei-maertens commented
Cleaned up a little bit to register the handler globally and enable it via option so we don't need the component with side-effect. Tested on mobile with storybook and the panning/dragging is smooth for me too.

2023-08-04 10:53 UTC, merged