:sparkles: [#483] add description to selectboxes and radio option
open-formulieren/open-forms-sdk pull request #664
Opened 2024-03-18 13:31 UTC by nikkiysendoorn1

2024-03-18 14:21 UTC, nikkiysendoorn1 commented
Renamed the branch, see here the previous PR: https://github.com/open-formulieren/open-forms-sdk/pull/658

2024-03-19 09:53 UTC, sergei-maertens requested changes

2024-03-19 09:53 UTC, sergei-maertens commented on src/formio/components/Checkbox.scss
> +
this appears to duplicate the lines below, no?

2024-03-19 09:53 UTC, sergei-maertens commented on src/formio/templates/radio.ejs
> +    aria-describedby="{{ctx.id}}{{ctx.row}}-{{item.value}}-description"
if there's no item description, there's an aria-describedby pointer to an ID that doesn't exist. That doesn't seem valid - probably best to only include the attribute if there is a description:

```suggestion
    {% if (item.description) %}aria-describedby="{{ctx.id}}{{ctx.row}}-{{item.value}}-description"{% } %}
```

2024-03-19 10:15 UTC, sergei-maertens approved these changes

2024-03-19 10:28 UTC, merged